/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

//import project.Kişi;
//import project.OtomasyonSistemi;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author oguzhan
 */
public class ProjectFrame extends javax.swing.JFrame {

    
/**
     * Creates new form Denek
     */
    Rooms r = new Rooms();
    private static SystemClass system = new SystemClass();
    static Object rowData[]=new Object[10];
    public static Scanner scan = new Scanner(System.in);
    
     ImageIcon myIcon = new ImageIcon(getClass().getResource("view.png"));
     ImageIcon newIcon = new ImageIcon(getClass().getResource("deluxe.png"));
     ImageIcon my2Icon = new ImageIcon(getClass().getResource("standart.png"));
     ImageIcon my3Icon = new ImageIcon(getClass().getResource("king.png"));
     ImageIcon searchIcon = new ImageIcon(getClass().getResource("search.png"));                   
     public ProjectFrame() {
      
         r.initial(system.PersonList);
   
        initComponents();
        DefaultTableModel model = (DefaultTableModel) mytable.getModel();
        
     int  a = system.PersonList.size();
       for(int i = 0;i<a;i++)
       {
       rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
       rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
       model.addRow(rowData);
          
       }
       jPanel3.setVisible(false);
       jrop.setVisible(false);
       jrbs.setVisible(false);
       jrbd.setVisible(false);
       jrbk.setVisible(false);
       jdelux.setVisible(false);
       slPan.setVisible(false);
       jstand.setVisible(false);
       jking.setVisible(false);
       jPList.setVisible(false);
       Jbdel.setVisible(false);
        jPanel2.setVisible(false);
        combok.setVisible(false);
        combod.setVisible(false);
        combos.setVisible(false);
        combosl.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlIcon = new javax.swing.JLabel();
        jbSearch = new javax.swing.JButton();
        bList = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        backBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPList = new javax.swing.JPanel();
        jldel = new javax.swing.JLabel();
        tfDel = new javax.swing.JTextField();
        jrbk = new javax.swing.JRadioButton();
        tfTc = new javax.swing.JTextField();
        jrbd = new javax.swing.JRadioButton();
        jlName = new javax.swing.JLabel();
        jrop = new javax.swing.JLabel();
        jlSurname = new javax.swing.JLabel();
        jlTc = new javax.swing.JLabel();
        jlDate = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jbutSearch = new javax.swing.JButton();
        JBedit = new javax.swing.JButton();
        Jbdel = new javax.swing.JButton();
        jbutAdd = new javax.swing.JButton();
        tftel = new javax.swing.JTextField();
        jltel = new javax.swing.JLabel();
        jlco = new javax.swing.JLabel();
        jrbs = new javax.swing.JRadioButton();
        tfSurname = new javax.swing.JTextField();
        tfDate = new com.toedter.calendar.JDateChooser();
        co = new com.toedter.calendar.JDateChooser();
        jrsl = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        slPan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        slex3 = new javax.swing.JRadioButton();
        slex2 = new javax.swing.JRadioButton();
        slex1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        combosl = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        slday = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jdelux = new javax.swing.JPanel();
        delday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dex1 = new javax.swing.JRadioButton();
        dex2 = new javax.swing.JRadioButton();
        dex3 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        combod = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jstand = new javax.swing.JPanel();
        stday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        stex1 = new javax.swing.JRadioButton();
        stex2 = new javax.swing.JRadioButton();
        stex3 = new javax.swing.JRadioButton();
        jbutton4 = new javax.swing.JButton();
        combos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jking = new javax.swing.JPanel();
        kday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kex1 = new javax.swing.JRadioButton();
        kex2 = new javax.swing.JRadioButton();
        kex3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        combok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/view.png"))); // NOI18N
        jlIcon.setText("a");
        jPanel1.add(jlIcon);
        jlIcon.setBounds(0, 0, 920, 300);

        jbSearch.setBackground(new java.awt.Color(255, 255, 255));
        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbSearch);
        jbSearch.setBounds(930, 170, 80, 37);

        bList.setBackground(new java.awt.Color(255, 255, 255));
        bList.setForeground(new java.awt.Color(0, 51, 51));
        bList.setText("LİST");
        bList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListActionPerformed(evt);
            }
        });
        jPanel1.add(bList);
        bList.setBounds(930, 20, 80, 37);

        bAdd.setBackground(new java.awt.Color(255, 255, 255));
        bAdd.setText("ADD");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        jPanel1.add(bAdd);
        bAdd.setBounds(930, 70, 80, 37);

        bEdit.setBackground(new java.awt.Color(255, 255, 255));
        bEdit.setText("EDİT");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel1.add(bEdit);
        bEdit.setBounds(930, 120, 80, 37);

        bDel.setBackground(new java.awt.Color(255, 255, 255));
        bDel.setText("DELETE");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        jPanel1.add(bDel);
        bDel.setBounds(930, 220, 80, 37);

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setForeground(new java.awt.Color(0, 204, 153));
        backBut.setText("Back");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        jPanel1.add(backBut);
        backBut.setBounds(1400, 50, 79, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/reception.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1100, 0, 280, 290);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1400, 10, 79, 25);

        jPList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jldel.setText("Enter The Customer NO");

        tfDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDelActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbk);
        jrbk.setText("KingSuite");
        jrbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbkActionPerformed(evt);
            }
        });

        tfTc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTcActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbd);
        jrbd.setText("Luxury");
        jrbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbdActionPerformed(evt);
            }
        });

        jlName.setText("Name");

        jrop.setText("~~~ ROOM OPTIONS ~~~");

        jlSurname.setText("Surname");

        jlTc.setText("Tc No");

        jlDate.setText("Check-in");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jbutSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/search.png"))); // NOI18N
        jbutSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutSearchActionPerformed(evt);
            }
        });

        JBedit.setText("OK");
        JBedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeditActionPerformed(evt);
            }
        });

        Jbdel.setText("OK");
        Jbdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbdelActionPerformed(evt);
            }
        });

        jbutAdd.setText("OK");
        jbutAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutAddActionPerformed(evt);
            }
        });

        tftel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelActionPerformed(evt);
            }
        });

        jltel.setText("Telephone");

        jlco.setText("Check-out");

        buttonGroup1.add(jrbs);
        jrbs.setText("Standart");
        jrbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbsActionPerformed(evt);
            }
        });

        tfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSurnameActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrsl);
        jrsl.setText("SuperLux");
        jrsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrslActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPListLayout = new javax.swing.GroupLayout(jPList);
        jPList.setLayout(jPListLayout);
        jPListLayout.setHorizontalGroup(
            jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addComponent(jbutAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBedit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jbdel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addComponent(jldel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbutSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addComponent(jlco, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDate, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPListLayout.createSequentialGroup()
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrop, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPListLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jrbk)
                                            .addComponent(jrbs, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jrsl))
                                        .addGap(17, 17, 17))))
                            .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addComponent(jlSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPListLayout.createSequentialGroup()
                            .addComponent(jltel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tftel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPListLayout.createSequentialGroup()
                            .addComponent(jlTc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfTc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPListLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlDate, jlName, jlSurname, jlTc, jldel, jltel});

        jPListLayout.setVerticalGroup(
            jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addComponent(jrop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbk)
                        .addGap(18, 18, 18)
                        .addComponent(jrbd)
                        .addGap(18, 18, 18)
                        .addComponent(jrbs)))
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jltel)
                            .addComponent(tftel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPListLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jrsl)))
                .addGap(26, 26, 26)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jldel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutSearch))
                .addGap(20, 20, 20)
                .addGroup(jPListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jbdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutAdd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPListLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlDate, jlName, jlSurname, jlTc, jldel, jltel});

        mytable.setBorder(new javax.swing.border.MatteBorder(null));
        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerNo", "Name", "Surname", "TC No", "Telephone", "RegistrationDate", "Check-Out", "RoomType", "TotalAmount", "RoomNo"
            }
        ));
        jScrollPane1.setViewportView(mytable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        slPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel8.setText("Super Lux");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sl..png"))); // NOI18N

        slex3.setText("Room for 4 people(+210$)");

        slex2.setText("Triple room(+150$)");

        slex1.setText("Double room(+100$)");

        jButton1.setText("Select Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        combosl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Z100", "Z101", "Z102", "Z103", "Z104", "Z105", "Z106", "Z107", "Z108", "Z110", "Z111", "Z112", "Z113", "Z114", "Z115", "Z116", "Z117" }));

        jLabel30.setText("How many Days  ?");

        jLabel31.setText("Parking ✔");

        jLabel32.setText("Mini bar ✔");

        jLabel33.setText("Jacuzzi ✔");

        jLabel34.setText("View ✔");

        jLabel35.setText("And More..");

        javax.swing.GroupLayout slPanLayout = new javax.swing.GroupLayout(slPan);
        slPan.setLayout(slPanLayout);
        slPanLayout.setHorizontalGroup(
            slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slPanLayout.createSequentialGroup()
                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(slPanLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(slPanLayout.createSequentialGroup()
                                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slex1)
                                    .addComponent(slex2)
                                    .addComponent(slex3)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(slday, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(slPanLayout.createSequentialGroup()
                                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(slPanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(18, 18, 18)
                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combosl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        slPanLayout.setVerticalGroup(
            slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slPanLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(slPanLayout.createSequentialGroup()
                        .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(slPanLayout.createSequentialGroup()
                                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(jButton1))
                                .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(slPanLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel32))
                                    .addGroup(slPanLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(combosl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(slPanLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(27, 27, 27)
                                .addComponent(slday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(slPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slex1)
                            .addGroup(slPanLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel33)
                                .addGap(13, 13, 13)
                                .addComponent(slex2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addGap(2, 2, 2)
                        .addComponent(slex3)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(slPan, "card5");

        jdelux.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        delday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deldayActionPerformed(evt);
            }
        });

        jLabel6.setText("46 inch LCD flat panel screen TV ✔");

        jLabel16.setText("How many Days ?");

        jLabel17.setText("Pool ✔");

        jLabel18.setText("Parking ✔");

        jLabel19.setText("Non-Smoking Hotel ✔");

        jLabel20.setText("Lutron Lighting systems ✔");

        jLabel21.setText("And More..");

        buttonGroup2.add(dex1);
        dex1.setText("Double room(+95$)");

        buttonGroup2.add(dex2);
        dex2.setText("Triple room(+100$)");

        buttonGroup2.add(dex3);
        dex3.setText("Room for 4 people(+180$)");
        dex3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dex3ActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/deluxe.png"))); // NOI18N

        jButton3.setText("Select Room");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        combod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L100", "L101", "L102", "L103", "L104", "L105", "L106", "L107", "L108", "L110", "L111", "L112", "L113", "L114", "L115", "L116", "L117" }));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel2.setText("Luxury");

        javax.swing.GroupLayout jdeluxLayout = new javax.swing.GroupLayout(jdelux);
        jdelux.setLayout(jdeluxLayout);
        jdeluxLayout.setHorizontalGroup(
            jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdeluxLayout.createSequentialGroup()
                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdeluxLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(31, 31, 31)
                        .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dex1)
                    .addComponent(dex2)
                    .addComponent(dex3)
                    .addComponent(delday, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jdeluxLayout.setVerticalGroup(
            jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdeluxLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jdeluxLayout.createSequentialGroup()
                        .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdeluxLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(30, 30, 30)
                                .addComponent(combod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdeluxLayout.createSequentialGroup()
                                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdeluxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdeluxLayout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jdeluxLayout.createSequentialGroup()
                                        .addComponent(dex1)
                                        .addGap(18, 18, 18)
                                        .addComponent(dex2)
                                        .addGap(18, 18, 18)
                                        .addComponent(dex3)))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))))
        );

        jPanel3.add(jdelux, "card3");

        jstand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jstand.setPreferredSize(new java.awt.Dimension(881, 279));

        stday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdayActionPerformed(evt);
            }
        });

        jLabel7.setText("Internet access ✔");

        jLabel23.setText("Balcony ✔");

        jLabel24.setText("View ✔");

        jLabel25.setText("Television ✔");

        jLabel26.setText("Lift ✔");

        jLabel27.setText("How many Day ?");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/standart.png"))); // NOI18N

        buttonGroup4.add(stex1);
        stex1.setText("Double room (+80$)");

        buttonGroup4.add(stex2);
        stex2.setText("Triple room (+140$)");

        buttonGroup4.add(stex3);
        stex3.setText("room for 4 people(+200$)");

        jbutton4.setText("Select Room");
        jbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton4ActionPerformed(evt);
            }
        });

        combos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S100", "S101", "S102", "S103", "S104", "S105", "S106", "S107", "S108", "S110", "S111", "S112", "S113", "S114", "S115", "S116", "S117" }));
        combos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel3.setText("Standart");

        javax.swing.GroupLayout jstandLayout = new javax.swing.GroupLayout(jstand);
        jstand.setLayout(jstandLayout);
        jstandLayout.setHorizontalGroup(
            jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstandLayout.createSequentialGroup()
                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel7)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stex2)
                    .addComponent(stex3)
                    .addGroup(jstandLayout.createSequentialGroup()
                        .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stday, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stex1))
                        .addGap(32, 32, 32)))
                .addGap(27, 27, 27)
                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbutton4)
                    .addComponent(combos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jstandLayout.setVerticalGroup(
            jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jstandLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jstandLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(stex1))
                            .addGroup(jstandLayout.createSequentialGroup()
                                .addComponent(jbutton4)
                                .addGap(46, 46, 46)
                                .addComponent(combos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(stex2)
                        .addGap(18, 18, 18)
                        .addComponent(stex3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jstandLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jstandLayout.createSequentialGroup()
                                .addGroup(jstandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jstandLayout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(jLabel25))
                                    .addGroup(jstandLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel24)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.add(jstand, "card2");

        jking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jking.setPreferredSize(new java.awt.Dimension(881, 279));

        kday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdayActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/king.png"))); // NOI18N

        jLabel9.setText("Free Internet ✔");

        jLabel10.setText("Ocean View ✔");

        jLabel11.setText("Jacuzzi ✔");

        jLabel12.setText("Mini-Bar ✔");

        jLabel13.setText("iPod Docking Station ✔");

        jLabel14.setText("And More..");

        jLabel15.setText("How many Day ?");

        buttonGroup3.add(kex1);
        kex1.setText("Double room(+175$)");
        kex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kex1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(kex2);
        kex2.setText("Triple room(+250$)");

        buttonGroup3.add(kex3);
        kex3.setText("Room for 4 people(400$)");

        jButton2.setText("Select Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        combok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "K100", "K101", "K102", "K103", "K104", "K105", "K106", "K107", "K108", "K110", "K111", "K112", "K113", "K114", "K115", "K116", "K117" }));
        combok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setText("KingSuite");

        javax.swing.GroupLayout jkingLayout = new javax.swing.GroupLayout(jking);
        jking.setLayout(jkingLayout);
        jkingLayout.setHorizontalGroup(
            jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jkingLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kex2)
                    .addComponent(kex3)
                    .addComponent(kex1)
                    .addComponent(kday, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(combok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jkingLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jkingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel9});

        jkingLayout.setVerticalGroup(
            jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkingLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jkingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(kday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addContainerGap())
                    .addGroup(jkingLayout.createSequentialGroup()
                        .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jkingLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kex1)
                                    .addComponent(combok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(kex2)
                                .addGap(18, 18, 18)
                                .addComponent(kex3))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jkingLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel13, jLabel9});

        jPanel3.add(jking, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(595, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        jrsl.setVisible(true);
        bListActionPerformed(evt);        
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jbutSearch.setVisible(false);
        jltel.setVisible(true);
        tftel.setVisible(true);
        jldel.setVisible(false);
        tfDel.setVisible(false);
        jbutAdd.setVisible(true);
       jPList.setVisible(true); 
       jPList.setVisible(true); 
       tfDate.setVisible(true);
       tfName.setVisible(true);
       tfSurname.setVisible(true);
       tfTc.setVisible(true);
       jlSurname.setVisible(true);
       jlDate.setVisible(true);
       jlName.setVisible(true);
       jlTc.setVisible(true);
       Jbdel.setVisible(false);
       JBedit.setVisible(false);
       jrop.setVisible(true);
       jrbs.setVisible(true);
       jrbd.setVisible(true);
       jrbk.setVisible(true);
       jlco.setVisible(true);
         co.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
         
        jrsl.setVisible(false);
        bListActionPerformed(evt);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jlco.setVisible(false);
         co.setVisible(false);
        jltel.setVisible(false);
         tftel.setVisible(false);
        jstand.setVisible(false);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jking.setVisible(false);
        jbutAdd.setVisible(false);
        tfDate.setVisible(false);
       tfName.setVisible(false);
       tfSurname.setVisible(false);
       tfTc.setVisible(false);
       jlSurname.setVisible(false);
       jlDate.setVisible(false);
       jlName.setVisible(false);
       jlTc.setVisible(false);
        jPList.setVisible(true);
        jldel.setVisible(true);
        tfDel.setVisible(true);
        Jbdel.setVisible(true);
        JBedit.setVisible(false);
      jrop.setVisible(false);
      jbutSearch.setVisible(false);
       jrbs.setVisible(false);
       jrbd.setVisible(false);
       jrbk.setVisible(false);
    }//GEN-LAST:event_bDelActionPerformed

    private void tfDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDelActionPerformed

    private void jbutAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutAddActionPerformed

        boolean flag = true;
        String rNo;
        double price;
     String room;
     if(jrbk.isSelected())
     {
         KingSuite k = new KingSuite(Integer.parseInt(kday.getText()));
         if(kex1.isSelected())
             k.addEx1();
         if(kex2.isSelected())
             k.addEx2();
         if(kex3.isSelected())
             k.addEx3();
         price = k.getTotalprice();
         room = k.getType();
          rNo = (String) combok.getSelectedItem();
     }
     else if(jrbd.isSelected())
     {
    Luxury d = new Luxury(Integer.parseInt(delday.getText()));
         if(dex1.isSelected())
             d.addEx1();
         if(dex2.isSelected())
             d.addEx2();
         if(dex3.isSelected())
             d.addEx3();
         price = d.getTotalprice();
         room = d.getType();
         rNo = (String) combod.getSelectedItem();
     }
     else if(jrbs.isSelected())
     {
     Standart s = new Standart(Integer.parseInt(stday.getText()));
         if(stex1.isSelected())
             s.addEx1();
         if(stex2.isSelected())
             s.addEx2();
         if(stex3.isSelected())
             s.addEx3();
         price = s.getTotalprice();
         room = s.getType();
         rNo = (String) combos.getSelectedItem();
     } 
     else
     {
     SuperLux sl = new SuperLux(Integer.parseInt(slday.getText()));
     if(slex1.isSelected())
     sl.addEx1();
     if(slex2.isSelected())
     sl.addEx2();
     if(slex3.isSelected())
     sl.addEx3();
   price = sl.getTotalprice();
   room = sl.getType();
   rNo = (String) combosl.getSelectedItem();
     }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy",Locale.getDefault());
        String d = sdf.format(tfDate.getDate());
        String d2 = sdf.format(co.getDate());
        for(int in = 0; in < system.PersonList.size();in++){
        if( rNo.equals(system.PersonList.get(in).getRoomNumber()) ){
            JOptionPane.showMessageDialog(null,"Please Change Your Room"); 
            flag = false;  
            break;
          }
        }
        
       
   if(  flag && system.addNewCustomer(Person.create2(tfName.getText(), tfSurname.getText(), Long.parseLong(tfTc.getText()),tftel.getText(),d,d2,room,price,rNo) ) ) {
        tfName.setText("");
        tfSurname.setText("");
        tfTc.setText("");
        tfDate.getDate();
        tftel.setText("");
       DefaultTableModel model = (DefaultTableModel) mytable.getModel(); 
     
        int a = system.PersonList.size();
       for(int i=0;i<a;i++)
       {
       rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
       rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
       }
       model.addRow(rowData);
  
  
   r.changeColor(rNo,'A');
    bListActionPerformed(evt);
    system.updateFile();
    r.setVisible(false);
   }
   else {
       if(flag == false)
       {}
       else{
       JOptionPane.showMessageDialog(null,"We already have customer who have "+tfTc.getText()+" TC no");
        tfName.setText("");
        tfSurname.setText("");
        tfTc.setText("");
        tftel.setText("");
   
         bListActionPerformed(evt);
               }
      
   }
        
        
    }//GEN-LAST:event_jbutAddActionPerformed

    private void JbdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbdelActionPerformed
      int j =  system.findPerson(Integer.parseInt(tfDel.getText()));
             
        if( j != -1 )
       {
           int t = JOptionPane.showConfirmDialog(null,"Do you really want to delete\n"+system.PersonList.get(j).getName()+"\n"+system.PersonList.get(j).getSurName()+"\n"+system.PersonList.get(j).getTC(),"Delete",JOptionPane.YES_NO_OPTION);
    if(t == 0)
    {
         r.changeColor(system.PersonList.get(j).getRoomNumber(), 'E');
          system.delTheCustomer(Integer.parseInt(tfDel.getText()));
           DefaultTableModel model = (DefaultTableModel) mytable.getModel(); 
         model.setRowCount(0);
         int a = system.PersonList.size();
       for(int i=0;i<a;i++)
       {
       rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
       rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
        model.addRow(rowData);
      }
       tfDel.setText("");
    }
    system.updateFile();
       }
       else
       {
      JOptionPane.showMessageDialog(null,"There is no customer with number "+tfDel.getText());
       }
    }//GEN-LAST:event_JbdelActionPerformed

    private void bListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListActionPerformed

        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jlco.setVisible(false);
        co.setVisible(false);
        jbutSearch.setVisible(false);
        jltel.setVisible(false);
        tftel.setVisible(false);
        jstand.setVisible(false);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jking.setVisible(false);
        jrop.setVisible(false);
        jrbs.setVisible(false);
        jrbd.setVisible(false);
        jrbk.setVisible(false);
        jldel.setVisible(false);
        tfDel.setVisible(false);
        jbutAdd.setVisible(false);
        tfDate.setVisible(false);
        tfName.setVisible(false);
        tfSurname.setVisible(false);
        tfTc.setVisible(false);
        jlSurname.setVisible(false);
        jlDate.setVisible(false);
        jlName.setVisible(false);
        jlTc.setVisible(false);
        jPList.setVisible(false);
        mytable.setVisible(true);
        JBedit.setVisible(false);
        Jbdel.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) mytable.getModel(); 
        model.setRowCount(0);
       int a = system.PersonList.size();
       for(int i=0;i<a;i++)
       {
       rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
        rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
        model.addRow(rowData);
      }
    }//GEN-LAST:event_bListActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
 jrsl.setVisible(true);
        bListActionPerformed(evt);
        jPanel3.setVisible(false);
        jlco.setVisible(true);
         co.setVisible(true);
        jltel.setVisible(true);
         tftel.setVisible(true);
        jstand.setVisible(false);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jking.setVisible(false);
        jrop.setVisible(true);
       jrbs.setVisible(true);
       jrbd.setVisible(true);
       jrbk.setVisible(true); 
        jbutAdd.setVisible(false);
      jPanel2.setVisible(true);
       Jbdel.setVisible(false);
       tfDate.setVisible(true);
       tfName.setVisible(true);
       tfSurname.setVisible(true);
       tfTc.setVisible(true);
       jlSurname.setVisible(true);
       jlDate.setVisible(true);
       jlName.setVisible(true);
       jlTc.setVisible(true);
       tfDel.setVisible(true);
       jldel.setVisible(true);
       jPList.setVisible(true);
       mytable.setVisible(true);
       JBedit.setVisible(true);
        jbutSearch.setVisible(false);
        
    }//GEN-LAST:event_bEditActionPerformed

    private void JBeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeditActionPerformed
     boolean flag = true;
     boolean test = false;
     String rNo;
     double price;
     String room;
     if(jrbk.isSelected())
     {
         KingSuite k = new KingSuite(Integer.parseInt(kday.getText()));
         if(kex1.isSelected())
             k.addEx1();
         if(kex2.isSelected())
             k.addEx2();
         if(kex3.isSelected())
             k.addEx3();
         price = k.getTotalprice();
         room = k.getType();
         rNo = (String) combok.getSelectedItem();
     }
     else if(jrbd.isSelected())
     {
    Luxury d = new Luxury(Integer.parseInt(delday.getText()));
         if(dex1.isSelected())
             d.addEx1();
         if(dex2.isSelected())
             d.addEx2();
         if(dex3.isSelected())
             d.addEx3();
         price = d.getTotalprice();
         room = d.getType();
          rNo = (String) combod.getSelectedItem();
     }
     else if(jrbs.isSelected())
     {
     Standart s = new Standart(Integer.parseInt(stday.getText()));
         if(stex1.isSelected())
             s.addEx1();
         if(stex2.isSelected())
             s.addEx2();
         if(stex3.isSelected())
             s.addEx3();
         price = s.getTotalprice();
         room = s.getType();
         rNo = (String) combos.getSelectedItem();
     }  
     else
     {
     SuperLux sl = new SuperLux(Integer.parseInt(slday.getText()));
         if(slex1.isSelected())
             sl.addEx1();
         if(slex2.isSelected())
             sl.addEx2();
         if(slex3.isSelected())
             sl.addEx3();
         price = sl.getTotalprice();
         room = sl.getType();
         rNo = (String) combosl.getSelectedItem();
     }
     
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy",Locale.getDefault());
        String d = sdf.format(tfDate.getDate());
        String d2 = sdf.format(co.getDate());
        String deg = system.PersonList.get(system.findPerson(Integer.parseInt(tfDel.getText()))).getRoomNumber();
       
        int findPerson = system.findPerson(Integer.parseInt(tfDel.getText()));
        for(int in = 0; in < system.PersonList.size();in++){
        if( rNo.equals(system.PersonList.get(in).getRoomNumber()) ){
             test = system.PersonList.get(findPerson).getRoomNumber().equals(system.PersonList.get(in).getRoomNumber());
            if(test)
                break;
            else{
            JOptionPane.showMessageDialog(null,"Please Change Your Room"); 
            flag = false;  
            break;
          }
         }
        }
        int i = system.EditTheCustomer(Integer.parseInt(tfDel.getText()),Person.create2(tfName.getText(),tfSurname.getText(), Long.parseLong(tfTc.getText()),tftel.getText(),d,d2,room,price,rNo));
       if(i != -1 && flag)
       {
      
        
        DefaultTableModel model = (DefaultTableModel) mytable.getModel();
        model.setRowCount(0);
        int a = system.PersonList.size();
       for( i=0;i<a;i++)
       {
       rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
       rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
        model.addRow(rowData);
      }        
        system.updateFile();
        tfName.setText("");
        tfSurname.setText("");
        tfTc.setText("");
        tfDel.setText("");
        tftel.setText("");
    if(test){
    }
    else
        r.changeColor(deg,'E');
  
    r.changeColor(rNo,'A');
    r.setVisible(false);
    }//GEN-LAST:event_JBeditActionPerformed
      else
       {
            if(flag == false)
       {}
            else{
        JOptionPane.showMessageDialog(null,"There is no customer with number "+tfDel.getText()); 
        tfName.setText("");
        tfSurname.setText("");
        tfTc.setText("");
        tftel.setText("");       
        tfDel.setText("");
       }
       }
    }
    
    
    private void jrbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbkActionPerformed
       combos.setVisible(false);
        combosl.setVisible(false);
        combod.setVisible(false);
         combok.setVisible(false);
        jPanel3.setVisible(true);
        jdelux.setVisible(false);
       jstand.setVisible(false);
       jking.setVisible(true);  
       slPan.setVisible(false);
       kday.setText("");
       stday.setText("");
       delday.setText("");
       slday.setText("");
    }//GEN-LAST:event_jrbkActionPerformed

    private void jrbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbdActionPerformed
 combos.setVisible(false);
        combosl.setVisible(false);
        combod.setVisible(false);
         combok.setVisible(false);
        jPanel3.setVisible(true);
        jdelux.setVisible(true);
       jstand.setVisible(false);
       slPan.setVisible(false);
       jking.setVisible(false);
       kday.setText("");
       stday.setText("");
       delday.setText("");
       slday.setText("");
    }//GEN-LAST:event_jrbdActionPerformed

    private void deldayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deldayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deldayActionPerformed

    private void stdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdayActionPerformed

    private void dex3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dex3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dex3ActionPerformed

    private void kdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdayActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        jrsl.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jlco.setVisible(false);
         co.setVisible(false);
        jltel.setVisible(false);
         tftel.setVisible(false);
        jstand.setVisible(false);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jking.setVisible(false);
        jbutAdd.setVisible(false);
        tfDate.setVisible(false);
       tfName.setVisible(false);
       tfSurname.setVisible(false);
       tfTc.setVisible(false);
       jlSurname.setVisible(false);
       jlDate.setVisible(false);
       jlName.setVisible(false);
       jlTc.setVisible(false);
        jPList.setVisible(true);
        jldel.setVisible(true);
        tfDel.setVisible(true);
        Jbdel.setVisible(false);
        JBedit.setVisible(false);
      jrop.setVisible(false);
       jrbs.setVisible(false);
       jrbd.setVisible(false);
       jrbk.setVisible(false);   
       jbutSearch.setVisible(true);
       
    }//GEN-LAST:event_jbSearchActionPerformed

    private void kex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kex1ActionPerformed

    private void jbutSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutSearchActionPerformed
       
        int i = system.inquireCustomer(Integer.parseInt( tfDel.getText() ));
        if(i == -1)
        JOptionPane.showMessageDialog(null,"There is no customer with number "+tfDel.getText());
        else
        {
        DefaultTableModel model = (DefaultTableModel) mytable.getModel(); 
        model.setRowCount(0);
        rowData[0] = system.PersonList.get(i).getcustomerNO();
       rowData[1] = system.PersonList.get(i).getName();
       rowData[2] = system.PersonList.get(i).getSurName();
       rowData[3] = system.PersonList.get(i).getTC();
       rowData[4] = system.PersonList.get(i).getTelNo();
       rowData[5] = system.PersonList.get(i).getDate();
       rowData[6] = system.PersonList.get(i).getDateOut();
       rowData[7] = system.PersonList.get(i).getRoomType();
       rowData[8] = system.PersonList.get(i).getLoan();
       rowData[9] = system.PersonList.get(i).getRoomNumber();
        model.addRow(rowData);
        }
        tfName.setText("");
        tfSurname.setText("");
        tfTc.setText("");
     //   tfDate.setText("");
        tfDel.setText("");
        tftel.setText("");
        
        
    }//GEN-LAST:event_jbutSearchActionPerformed

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
    Login log = new Login();  
    log.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backButActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPList.setVisible(false);
        jking.setVisible(false);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jstand.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jrbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbsActionPerformed
 combos.setVisible(false);
        combosl.setVisible(false);
        combod.setVisible(false);
         combok.setVisible(false);
        jPanel3.setVisible(true);
        jdelux.setVisible(false);
        slPan.setVisible(false);
        jstand.setVisible(true);
        jking.setVisible(false);
        kday.setText("");
        stday.setText("");
        delday.setText("");
        slday.setText("");
    }//GEN-LAST:event_jrbsActionPerformed

    private void tftelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelActionPerformed

    private void tfSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSurnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        combok.setVisible(true);
        r.setVisible(true);
        //r.appearK();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokActionPerformed

    private void combosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosActionPerformed

    private void jbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton4ActionPerformed
      // for(int i = 0; i< system.PersonList.size();i++)
     //if(    system.PersonList.get(i).getRoomNumber() == combos.getItemAt(i) )
        
                 
        combos.setVisible(true);
        r.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        combod.setVisible(true);
        r.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfTcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTcActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       combosl.setVisible(true);
       r.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrslActionPerformed
 combos.setVisible(false);
        combosl.setVisible(false);
        combod.setVisible(false);
         combok.setVisible(false);
        jPanel3.setVisible(true);
        jdelux.setVisible(false);
        jstand.setVisible(false);
        jking.setVisible(false);
        slPan.setVisible(true);
        kday.setText("");
        stday.setText("");
        delday.setText("");
        slday.setText("");
    }//GEN-LAST:event_jrslActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void maina(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectFrame().setVisible(true);
            }
        });
    }
     
 

    
        
        
       
        
    

   
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBedit;
    private javax.swing.JButton Jbdel;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bList;
    private javax.swing.JButton backBut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private com.toedter.calendar.JDateChooser co;
    private javax.swing.JComboBox<String> combod;
    private javax.swing.JComboBox<String> combok;
    private javax.swing.JComboBox<String> combos;
    private javax.swing.JComboBox<String> combosl;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JTextField delday;
    private javax.swing.JRadioButton dex1;
    private javax.swing.JRadioButton dex2;
    private javax.swing.JRadioButton dex3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSearch;
    private javax.swing.JButton jbutAdd;
    private javax.swing.JButton jbutSearch;
    private javax.swing.JButton jbutton4;
    private javax.swing.JPanel jdelux;
    private javax.swing.JPanel jking;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSurname;
    private javax.swing.JLabel jlTc;
    private javax.swing.JLabel jlco;
    private javax.swing.JLabel jldel;
    private javax.swing.JLabel jltel;
    private javax.swing.JRadioButton jrbd;
    private javax.swing.JRadioButton jrbk;
    private javax.swing.JRadioButton jrbs;
    private javax.swing.JLabel jrop;
    private javax.swing.JRadioButton jrsl;
    private javax.swing.JPanel jstand;
    private javax.swing.JTextField kday;
    private javax.swing.JRadioButton kex1;
    private javax.swing.JRadioButton kex2;
    private javax.swing.JRadioButton kex3;
    private javax.swing.JTable mytable;
    private javax.swing.JPanel slPan;
    private javax.swing.JTextField slday;
    private javax.swing.JRadioButton slex1;
    private javax.swing.JRadioButton slex2;
    private javax.swing.JRadioButton slex3;
    private javax.swing.JTextField stday;
    private javax.swing.JRadioButton stex1;
    private javax.swing.JRadioButton stex2;
    private javax.swing.JRadioButton stex3;
    private com.toedter.calendar.JDateChooser tfDate;
    private javax.swing.JTextField tfDel;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSurname;
    private javax.swing.JTextField tfTc;
    private javax.swing.JTextField tftel;
    // End of variables declaration//GEN-END:variables

}

    
